name: Build and Test

on:
  workflow_call: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check-cabal:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/check-cabal.yaml@v4
    secrets: inherit

  build-with-ghc-9-2:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "9.2"
      skip-doctest: true
      skip-benchmarks: true
      test-options: >
        --qc-max-success=10000
  
  build-with-latest:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      skip-doctest: true
      test-options: >
        --qc-max-success=10000
